{
 "title": "Dashboard for PyTorch Simple Model",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nv_gpu_utilization{job=\"triton\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nv_gpu_power_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_energy_consumption", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Memory Used (in GB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes / (1024 * 1024 * 1024)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Inference Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nv_inference_count{job=\"triton\"}[$__rate_interval])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Inference Request Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_inference_request_failure{model=\"simple_model_gpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Request Pending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_inference_pending_request_count{model=\"simple_model_gpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Request Success",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_inference_request_success{model=\"simple_model_gpu\"}",
     "legendFormat": "{{model}}"
    }
   ]
  }
 ]
}